# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b797df83356b3fca431b6400475a9c93e265279e48403794527c6ecb611e72d266afd799e93618f535bf739acc642ba26ad99a03bc1a2a74a81c1b6ebfd03564

test:
  secret_key_base: f45141d6315fe20c2882d66903aff5e0d88f6b8eaa319c3385f6e1ba90b296ba4c0e38a4172802e4bcc03809797e3e39feeb974eacccf0f5d0bcb69bbb382244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
